# Base configs
baseurl: ""
url: "http://localhost:4000"
image_people_full: "/images/people/fulls"
image_people_thumb: "/images/people/thumbs"
image_general_full: "/images/general/fulls"
image_general_thumb: "/images/general/thumbs"
google_analytics: ""

# UI configs
title: "Lelen Abeywardena"
subtitle: "stuff about photos"
author: "Lelen Abeywardena"
bio: "Everything is still under construction"
publicise: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/NomadShotz-535849426803489"
  instagram: "https://www.instagram.com/nomadshotz"
  linkedin: "https://in.linkedin.com/in/lelen-abeywardena-19086592"
  github: "https://www.github.com/lelenabey"
  